### ISSUE TITLE
Project Abstrct

### ISSUE THREAD

**Issue by pallabrath** [bishnuprasadpanda/Export#1]
- we need to prepare the first epic for this project.

**Comment by bishnuprasadpanda** [comment]
A large number of databases (RDBMS, NOSQL) are currently gaining a lot of market space. The challenge faced by most enterprises and systems is to migrate data from one database (RDBMS or NOSQL) to another database (RDBMS or NOSQL). There are two aspects to it, One time data migration and real time data migration.

One time data migration involves , extracting the data, transforming the data and loading the data to the new database. This can be asynchronous and offline.

Real time data migration involves extracting, transforming and loading the data in real time efficiently  and optimally.
